"""Pack install / uninstall with ledger + marker-block hygiene (R2, R3, R7).

Install flow
------------

1. Resolve `target` (project root containing ``.claude/`` or
   ``$HOME``). The installer writes under:

   * ``~/.config/bcli/queries/<profile>.yaml`` — saved queries
   * ``~/.config/bcli/batches/<profile>/`` — batch templates
   * ``~/.config/bcli/registries/<profile>.json`` — registry presets
   * ``<target>/.claude/agent.d/bcli-<pack>/<fragment-name>`` — one
     fragment file per pack-fragment (single source of truth on disk)
   * ``<target>/AGENTS.md`` and/or ``<target>/CLAUDE.md`` — marker
     blocks per fragment ``targets`` list (R3)

2. Conflict check (R7): every endpoint we'd install gets compared
   against ledgers of *other* packs; refuses install unless
   ``--replace-owned --accept-conflicts``.

3. Build a plan; if ``--dry-run`` print and return. Otherwise
   atomically write each artefact (reused ``_atomic_write`` pattern
   from skill_init_cmd.py).

4. Persist a :class:`Ledger` so uninstall can find every artefact.

Uninstall
---------

Reads the ledger, deletes each path, strips marker blocks from
AGENTS.md / CLAUDE.md, then removes the ledger. Anything missing
or hand-edited surfaces as a warning; the rest still gets cleaned.
"""

from __future__ import annotations

import json
import logging
import os
import re
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from bcli.packs._ledger import (
    Ledger,
    LedgerEntry,
    LedgerRegistryEntry,
    build_ledger,
    delete_ledger,
    hash_content,
    list_ledgers,
    read_ledger,
    write_ledger,
)
from bcli.packs._protocol import (
    AgentFragment,
    Pack,
    PackQuery,
    TARGET_AGENTS,
    TARGET_CLAUDE,
)

logger = logging.getLogger("bcli.packs")


class InstallError(Exception):
    """Raised by the installer on validation / conflict failures."""


# ─── Plan / result dataclasses ──────────────────────────────────────


@dataclass
class InstallPlan:
    """The set of writes ``install_pack`` would perform.

    Pure data — ``execute()`` is the side-effecting step. Dry-run
    surfaces this directly.
    """

    pack: Pack
    profile: str
    target: Path
    fragment_writes: list["PlannedFragment"] = field(default_factory=list)
    query_writes: list["PlannedQuery"] = field(default_factory=list)
    batch_writes: list["PlannedBatch"] = field(default_factory=list)
    preset_writes: list["PlannedPreset"] = field(default_factory=list)
    block_writes: list["PlannedBlock"] = field(default_factory=list)
    conflicts: list["EndpointConflict"] = field(default_factory=list)


@dataclass
class PlannedFragment:
    fragment: AgentFragment
    path: Path
    rendered_hash: str


@dataclass
class PlannedQuery:
    query: PackQuery
    path: Path  # queries file
    rendered_hash: str


@dataclass
class PlannedBatch:
    filename: str
    path: Path
    rendered_hash: str


@dataclass
class PlannedPreset:
    name: str
    body: dict
    rendered_hash: str
    target_path: Path  # registries/<profile>.json


@dataclass
class PlannedBlock:
    target_file: Path
    block_id: str
    rendered: str
    rendered_hash: str


@dataclass
class EndpointConflict:
    endpoint: str
    incumbent_pack: str
    incumbent_version: str


# ─── Path helpers ───────────────────────────────────────────────────


def config_dir(*, override: Path | None = None) -> Path:
    return override or (Path.home() / ".config" / "bcli")


def queries_path(profile: str, *, override: Path | None = None) -> Path:
    return config_dir(override=override) / "queries" / f"{profile}.yaml"


def batches_dir(profile: str, *, override: Path | None = None) -> Path:
    return config_dir(override=override) / "batches" / profile


def registries_path(profile: str, *, override: Path | None = None) -> Path:
    return config_dir(override=override) / "registries" / f"{profile}.json"


def fragments_dir(target: Path, pack_name: str) -> Path:
    return target / ".claude" / "agent.d" / f"bcli-{pack_name}"


def resolve_target(target: Path | None = None) -> Path:
    """Pick the install target dir.

    1. Explicit ``target`` wins.
    2. CWD with ``.claude/`` → CWD (project convention).
    3. Otherwise ``$HOME``.
    """
    if target is not None:
        return Path(target)
    cwd = Path.cwd()
    if (cwd / ".claude").is_dir():
        return cwd
    return Path.home()


# ─── Marker block helpers (R3) ──────────────────────────────────────


def block_id_for(pack_name: str, fragment_name: str) -> str:
    return f"bcli-pack:{pack_name}:{fragment_name}"


def _start_marker(block_id: str) -> str:
    return (
        f"<!-- {block_id} START — generated by `bcli pack install`. "
        f"Edit the pack source, not this block. -->"
    )


def _end_marker(block_id: str, *, content_hash: str) -> str:
    return f"<!-- {block_id} END content_hash: {content_hash} -->"


def render_block(
    *, block_id: str, fragment: AgentFragment, content_hash: str
) -> str:
    return (
        f"{_start_marker(block_id)}\n"
        f"{fragment.content.rstrip()}\n"
        f"{_end_marker(block_id, content_hash=content_hash)}\n"
    )


_MARKER_RE_TPL = (
    r"(?:\n)?<!-- {bid} START.*?-->\n.*?<!-- {bid} END[^>]*-->\n?"
)


def _splice_block(existing: str, block_id: str, rendered: str) -> str:
    """Insert (or replace) a marker block in ``existing``.

    If the block is already there, it gets replaced in place. Otherwise
    we append it at the end with a leading blank line so the file
    stays readable.
    """
    pattern = re.compile(
        _MARKER_RE_TPL.format(bid=re.escape(block_id)),
        flags=re.DOTALL,
    )
    if pattern.search(existing):
        return pattern.sub("\n" + rendered, existing)
    # Append.
    if existing and not existing.endswith("\n"):
        existing += "\n"
    return existing + ("\n" if existing else "") + rendered


def _strip_block(existing: str, block_id: str) -> tuple[str, bool]:
    """Remove a marker block from ``existing``.

    Returns ``(new_text, found)``. ``found=False`` means the block
    wasn't present — uninstall surfaces that as "ledger says we
    installed it but it's already gone."
    """
    pattern = re.compile(
        _MARKER_RE_TPL.format(bid=re.escape(block_id)),
        flags=re.DOTALL,
    )
    new_text, n = pattern.subn("", existing)
    return new_text.rstrip() + "\n" if new_text.strip() else "", n > 0


# ─── Atomic write (reused from skill_init pattern) ─────────────────


def _atomic_write(path: Path, data: str) -> None:
    """Mirror of `bcli_cli.commands.skill_init_cmd._atomic_write`.

    Duplicated here rather than imported to keep the SDK->CLI
    dependency arrow pointing the right way (packs is SDK; we never
    want SDK code importing CLI modules). The behaviour is byte-
    identical: tmp file in the same directory, then os.replace.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=path.name + ".", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(data)
        os.replace(tmp_name, str(path))
    except Exception:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


# ─── Planning ───────────────────────────────────────────────────────


def plan_install(
    pack: Pack,
    *,
    profile: str,
    target: Path | None = None,
    config_override: Path | None = None,
) -> InstallPlan:
    """Build the install plan without touching disk."""
    plan = InstallPlan(
        pack=pack,
        profile=profile,
        target=resolve_target(target),
    )
    frag_root = fragments_dir(plan.target, pack.name)

    # Fragments — one file each + marker blocks per target.
    for f in pack.contents.agent_fragments:
        rendered_hash = hash_content(f.content)
        path = frag_root / f.name
        plan.fragment_writes.append(
            PlannedFragment(fragment=f, path=path, rendered_hash=rendered_hash)
        )
        bid = block_id_for(pack.name, f.name)
        rendered_block = render_block(
            block_id=bid, fragment=f, content_hash=rendered_hash
        )
        for tgt in f.targets:
            target_file = _block_target_file(plan.target, tgt)
            plan.block_writes.append(PlannedBlock(
                target_file=target_file,
                block_id=bid,
                rendered=rendered_block,
                rendered_hash=rendered_hash,
            ))

    # Queries — single YAML merge file.
    if pack.contents.queries:
        qpath = queries_path(profile, override=config_override)
        for q in pack.contents.queries:
            body_serialised = yaml.safe_dump(
                q.body, sort_keys=False, default_flow_style=False
            )
            plan.query_writes.append(PlannedQuery(
                query=q,
                path=qpath,
                rendered_hash=hash_content(body_serialised),
            ))

    # Batches — one file each.
    bdir = batches_dir(profile, override=config_override)
    for b in pack.contents.batches:
        plan.batch_writes.append(PlannedBatch(
            filename=b.filename,
            path=bdir / b.filename,
            rendered_hash=hash_content(b.body),
        ))

    # Registry presets — merged into one JSON file.
    if pack.contents.registry_presets:
        rpath = registries_path(profile, override=config_override)
        for preset in pack.contents.registry_presets:
            body_with_prov = dict(preset.body)
            body_with_prov["source_pack"] = pack.name
            body_with_prov["pack_version"] = pack.version
            plan.preset_writes.append(PlannedPreset(
                name=preset.name,
                body=body_with_prov,
                rendered_hash=hash_content(json.dumps(body_with_prov, sort_keys=True)),
                target_path=rpath,
            ))

    # Conflict detection — read every other pack's ledger.
    incumbents: dict[str, tuple[str, str]] = {}
    for other in list_ledgers(profile, config_dir=config_override):
        if other.pack_name == pack.name:
            continue
        for ep in other.registry_endpoints:
            incumbents[ep.name] = (other.pack_name, other.pack_version)
    for preset in plan.preset_writes:
        if preset.name in incumbents:
            owner, ver = incumbents[preset.name]
            plan.conflicts.append(EndpointConflict(
                endpoint=preset.name,
                incumbent_pack=owner,
                incumbent_version=ver,
            ))

    return plan


def _block_target_file(target: Path, target_kind: str) -> Path:
    if target_kind == TARGET_AGENTS:
        return target / "AGENTS.md"
    if target_kind == TARGET_CLAUDE:
        return target / "CLAUDE.md"
    raise InstallError(f"unknown fragment target: {target_kind!r}")


# ─── Execution ──────────────────────────────────────────────────────


def execute_install(
    plan: InstallPlan,
    *,
    config_override: Path | None = None,
    replace_owned: bool = False,
    accept_conflicts: bool = False,
) -> Ledger:
    """Apply ``plan`` to disk; persist the ledger; return it.

    Raises :class:`InstallError` on registry conflicts unless the
    caller passed ``replace_owned=True`` AND ``accept_conflicts=True``
    (R7 — two flags so neither accidental).
    """
    if plan.conflicts and not (replace_owned and accept_conflicts):
        lines = [
            f"  - {c.endpoint} (already owned by {c.incumbent_pack} v{c.incumbent_version})"
            for c in plan.conflicts
        ]
        raise InstallError(
            "Registry preset conflict — refusing to overwrite endpoints owned"
            " by another pack. Pass --replace-owned --accept-conflicts to"
            " override.\n" + "\n".join(lines)
        )

    written: list[LedgerEntry] = []

    # Fragments first — write content files.
    for pf in plan.fragment_writes:
        _atomic_write(pf.path, pf.fragment.content)
        written.append(LedgerEntry(
            kind="fragment_file",
            path=str(pf.path),
            rendered_hash=pf.rendered_hash,
            owner=plan.pack.name,
        ))

    # Marker blocks — for each target file, accumulate per-block updates
    # then write once.
    by_target: dict[Path, list[PlannedBlock]] = {}
    for blk in plan.block_writes:
        by_target.setdefault(blk.target_file, []).append(blk)
    for target_file, blocks in by_target.items():
        existing = (
            target_file.read_text(encoding="utf-8")
            if target_file.is_file() else ""
        )
        updated = existing
        for blk in blocks:
            updated = _splice_block(updated, blk.block_id, blk.rendered)
            written.append(LedgerEntry(
                kind="agents_block" if blk.target_file.name == "AGENTS.md"
                     else "claude_block",
                path=str(target_file),
                rendered_hash=blk.rendered_hash,
                owner=plan.pack.name,
                block_id=blk.block_id,
            ))
        _atomic_write(target_file, updated)

    # Queries — read-merge-write the YAML.
    if plan.query_writes:
        qpath = plan.query_writes[0].path
        existing_raw: dict = {}
        if qpath.is_file():
            try:
                existing_raw = (
                    yaml.safe_load(qpath.read_text(encoding="utf-8")) or {}
                )
            except yaml.YAMLError as e:
                raise InstallError(
                    f"existing {qpath} is not valid YAML: {e}"
                ) from e
        if not isinstance(existing_raw, dict):
            raise InstallError(f"{qpath}: top-level must be a mapping")
        existing_queries = existing_raw.get("queries") or {}
        if not isinstance(existing_queries, dict):
            raise InstallError(
                f"{qpath}: 'queries' must be a mapping"
            )
        for pq in plan.query_writes:
            body = dict(pq.query.body)
            body.setdefault("provenance", {})
            body["provenance"] = {
                "source_pack": plan.pack.name,
                "pack_version": plan.pack.version,
            }
            existing_queries[pq.query.name] = body
            written.append(LedgerEntry(
                kind="query",
                path=f"{qpath}#{pq.query.name}",
                rendered_hash=pq.rendered_hash,
                owner=plan.pack.name,
            ))
        existing_raw["queries"] = existing_queries
        text = yaml.safe_dump(existing_raw, sort_keys=False, default_flow_style=False)
        _atomic_write(qpath, text)

    # Batches.
    for pb in plan.batch_writes:
        body = next(
            b.body for b in plan.pack.contents.batches if b.filename == pb.filename
        )
        _atomic_write(pb.path, body)
        written.append(LedgerEntry(
            kind="batch",
            path=str(pb.path),
            rendered_hash=pb.rendered_hash,
            owner=plan.pack.name,
        ))

    # Registry presets — merge into JSON.
    registry_entries: list[LedgerRegistryEntry] = []
    if plan.preset_writes:
        rpath = plan.preset_writes[0].target_path
        existing_reg: dict = {}
        if rpath.is_file():
            try:
                existing_reg = json.loads(rpath.read_text(encoding="utf-8"))
            except json.JSONDecodeError as e:
                raise InstallError(
                    f"existing {rpath} is not valid JSON: {e}"
                ) from e
        # The runtime registry loader (`bcli.registry._registry`) reads
        # `endpoints` as a JSON array of entry objects, each keyed by its
        # `entity_set_name`. Write that shape — not a name→body map — so
        # pack-installed presets are actually resolvable at query time.
        endpoints = existing_reg.get("endpoints") or []
        if not isinstance(endpoints, list):
            raise InstallError(
                f"{rpath}: 'endpoints' must be a JSON array"
            )
        index_by_name: dict[str, int] = {}
        for i, entry in enumerate(endpoints):
            if isinstance(entry, dict):
                key = entry.get("entity_set_name")
                if key:
                    index_by_name[key] = i
        for preset in plan.preset_writes:
            body = dict(preset.body)
            body.setdefault("entity_set_name", preset.name)
            key = body["entity_set_name"]
            existing_idx = index_by_name.get(key)
            if existing_idx is not None:
                endpoints[existing_idx] = body
            else:
                index_by_name[key] = len(endpoints)
                endpoints.append(body)
            registry_entries.append(LedgerRegistryEntry(
                name=preset.name,
                rendered_hash=preset.rendered_hash,
                owner=plan.pack.name,
            ))
            written.append(LedgerEntry(
                kind="registry_preset",
                path=f"{rpath}#{preset.name}",
                rendered_hash=preset.rendered_hash,
                owner=plan.pack.name,
            ))
        existing_reg["endpoints"] = endpoints
        _atomic_write(rpath, json.dumps(existing_reg, indent=2))

    ledger = build_ledger(
        plan.pack,
        profile=plan.profile,
        target=plan.target,
        paths=written,
        registry_endpoints=registry_entries,
    )
    write_ledger(ledger, config_dir=config_override)
    return ledger


def install_pack(
    pack: Pack,
    *,
    profile: str,
    target: Path | None = None,
    dry_run: bool = False,
    replace_owned: bool = False,
    accept_conflicts: bool = False,
    config_override: Path | None = None,
) -> InstallPlan:
    """High-level wrapper: plan → optionally execute → return the plan.

    The plan is returned in both modes so the caller can render a
    diff in dry-run mode and a summary in execute mode.
    """
    plan = plan_install(
        pack,
        profile=profile,
        target=target,
        config_override=config_override,
    )
    if dry_run:
        return plan
    execute_install(
        plan,
        config_override=config_override,
        replace_owned=replace_owned,
        accept_conflicts=accept_conflicts,
    )
    return plan


# ─── Uninstall ──────────────────────────────────────────────────────


@dataclass
class UninstallResult:
    """Report from :func:`uninstall_pack`."""

    pack_name: str
    files_removed: list[Path] = field(default_factory=list)
    blocks_removed: list[tuple[Path, str]] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


def uninstall_pack(
    pack_name: str,
    *,
    profile: str,
    config_override: Path | None = None,
) -> UninstallResult:
    """Reverse a prior install using the persisted ledger.

    Anything missing from disk surfaces as a warning rather than an
    error — the user may have hand-deleted a fragment file, and we
    don't want to block the rest of cleanup over that.
    """
    result = UninstallResult(pack_name=pack_name)
    ledger = read_ledger(pack_name, profile, config_dir=config_override)
    if ledger is None:
        result.warnings.append(
            f"no install ledger found for pack {pack_name!r} on profile "
            f"{profile!r}; nothing to do"
        )
        return result

    # Group block entries by their target file so we touch each file once.
    block_paths: dict[Path, list[str]] = {}
    files_to_remove: list[Path] = []
    query_keys: list[tuple[Path, str]] = []
    preset_keys: list[tuple[Path, str]] = []

    for entry in ledger.paths:
        if entry.kind in {"agents_block", "claude_block"}:
            block_paths.setdefault(Path(entry.path), []).append(entry.block_id)
        elif entry.kind in {"fragment_file", "batch"}:
            files_to_remove.append(Path(entry.path))
        elif entry.kind == "query":
            file, _, name = entry.path.partition("#")
            if name:
                query_keys.append((Path(file), name))
        elif entry.kind == "registry_preset":
            file, _, name = entry.path.partition("#")
            if name:
                preset_keys.append((Path(file), name))

    # Strip marker blocks.
    for target_file, ids in block_paths.items():
        if not target_file.is_file():
            result.warnings.append(
                f"target file {target_file} missing — cannot strip blocks"
            )
            continue
        text = target_file.read_text(encoding="utf-8")
        for bid in ids:
            text, found = _strip_block(text, bid)
            if found:
                result.blocks_removed.append((target_file, bid))
            else:
                result.warnings.append(
                    f"block {bid} not present in {target_file}"
                )
        _atomic_write(target_file, text)

    # Remove standalone files (fragments, batches).
    for path in files_to_remove:
        if path.is_file():
            try:
                path.unlink()
                result.files_removed.append(path)
            except OSError as e:
                result.warnings.append(f"could not remove {path}: {e}")
        else:
            result.warnings.append(f"file {path} already missing")

    # Remove orphan fragment dir if empty.
    fragment_root = (
        files_to_remove[0].parent
        if files_to_remove and files_to_remove[0].parent.name.startswith("bcli-")
        else None
    )
    if fragment_root and fragment_root.is_dir():
        try:
            fragment_root.rmdir()  # only succeeds if empty
        except OSError:
            pass

    # Remove queries from the merged YAML.
    if query_keys:
        qpath = query_keys[0][0]
        if qpath.is_file():
            raw = yaml.safe_load(qpath.read_text(encoding="utf-8")) or {}
            queries = raw.get("queries") or {}
            for _, name in query_keys:
                if name in queries:
                    del queries[name]
            raw["queries"] = queries
            _atomic_write(
                qpath,
                yaml.safe_dump(raw, sort_keys=False, default_flow_style=False),
            )

    # Remove registry presets.
    if preset_keys:
        rpath = preset_keys[0][0]
        if rpath.is_file():
            try:
                raw = json.loads(rpath.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                raw = {}
            endpoints = raw.get("endpoints") or []
            if isinstance(endpoints, list):
                remove = {name for _, name in preset_keys}
                endpoints = [
                    e for e in endpoints
                    if not (isinstance(e, dict) and e.get("entity_set_name") in remove)
                ]
            raw["endpoints"] = endpoints
            _atomic_write(rpath, json.dumps(raw, indent=2))

    delete_ledger(pack_name, profile, config_dir=config_override)
    return result


__all__ = [
    "EndpointConflict",
    "InstallError",
    "InstallPlan",
    "PlannedBatch",
    "PlannedBlock",
    "PlannedFragment",
    "PlannedPreset",
    "PlannedQuery",
    "UninstallResult",
    "batches_dir",
    "block_id_for",
    "config_dir",
    "execute_install",
    "fragments_dir",
    "install_pack",
    "plan_install",
    "queries_path",
    "registries_path",
    "render_block",
    "resolve_target",
    "uninstall_pack",
]
