"""Convert an :class:`ExtractionResult` into the artefacts a reviewer needs.

Two files, side by side:

1. ``<input>.batch.yaml`` — the workflow the operator runs through
   ``bcli batch run …`` after review. Uses the schema's ``output``
   block to map extracted fields → BC field names and emits a
   ``${{ params.<parent_param> }}`` placeholder when the schema
   declares a parent linkage.

2. ``<input>.extracted.json`` — the traceability sidecar. Holds every
   extracted record verbatim, the model that produced it, token usage,
   warnings, and per-record source-page references back into the PDF.
   The reviewer cross-checks values in this file against the PDF
   itself before running the batch.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from bcli.extract._protocol import ExtractionResult
from bcli.extract._schema import ExtractSchema


def render_batch_yaml(
    result: ExtractionResult,
    schema: ExtractSchema,
    *,
    source_pdf: Path,
) -> str:
    """Render a ``bcli batch run``-compatible YAML string.

    One step per extracted record, ``${{ params.<parent_param> }}``
    placeholder for the parent linkage if the schema declares one.
    """
    workflow: dict[str, Any] = {
        "name": f"Load {schema.name} from {source_pdf.name}",
    }
    params_block = _build_params_block(schema)
    if params_block:
        workflow["params"] = params_block

    steps: list[dict[str, Any]] = []
    for i, record in enumerate(result.records, start=1):
        steps.append(_build_step(record.fields, schema, index=i))
    workflow["steps"] = steps

    header = _build_header_comment(result, schema, source_pdf)
    body = yaml.safe_dump(workflow, sort_keys=False, allow_unicode=True)
    return header + body


def render_sidecar_json(
    result: ExtractionResult,
    schema: ExtractSchema,
    *,
    source_pdf: Path,
) -> str:
    """Render the traceability sidecar as a pretty-printed JSON string."""
    payload = {
        "schema": {
            "name": schema.name,
            "description": schema.description,
            "list": schema.list,
            "output_endpoint": schema.output.endpoint,
        },
        "source_pdf": str(source_pdf),
        "extracted_at": datetime.now(timezone.utc).isoformat(),
        "model": result.model,
        "usage": {
            "input_tokens": result.input_tokens,
            "output_tokens": result.output_tokens,
        },
        "warnings": result.warnings,
        "records": [
            {
                "fields": rec.fields,
                "source_pages": list(rec.source_pages),
                "raw": rec.raw,
            }
            for rec in result.records
        ],
    }
    return json.dumps(payload, indent=2, default=_json_default)


# ─── Internals ───────────────────────────────────────────────────────


def _build_header_comment(
    result: ExtractionResult,
    schema: ExtractSchema,
    source_pdf: Path,
) -> str:
    lines = [
        "# Auto-generated by bcli extract. Review against the PDF before running.",
        f"# Source PDF       : {source_pdf}",
        f"# Schema           : {schema.name}",
        f"# Records extracted: {len(result.records)}",
        f"# Model            : {result.model or 'n/a'}",
        f"# Sidecar          : {source_pdf.stem}.extracted.json (per-field source pages)",
        "#",
        "# Recommended landing sequence:",
        "#   1. Read the sidecar, eyeball every record against the PDF.",
        "#   2. bcli batch run THIS_FILE --profile sandbox --dry-run",
        "#   3. bcli batch run THIS_FILE --profile sandbox",
        "#   4. Verify in the BC sandbox UI.",
        "#   5. bcli batch run THIS_FILE --profile production",
        "#",
    ]
    for w in result.warnings:
        lines.append(f"# WARNING: {w}")
    if result.warnings:
        lines.append("#")
    return "\n".join(lines) + "\n"


def _build_params_block(schema: ExtractSchema) -> dict[str, Any]:
    params: dict[str, Any] = {}
    if schema.output.parent_param:
        params[schema.output.parent_param] = {
            "description": (
                f"systemId of the parent {schema.output.parent_field} record "
                "(fill in before running)."
            ),
            "required": True,
        }
    return params


def _build_step(
    record_fields: dict[str, Any],
    schema: ExtractSchema,
    *,
    index: int,
) -> dict[str, Any]:
    data: dict[str, Any] = {}
    # Constants from schema first (so extracted values can override if
    # someone authored a schema that intentionally collides; the field_map
    # entries below also do not collide unless the schema author duplicates).
    for k, v in schema.output.constants.items():
        data[k] = v
    # Field map: BC field name ← extracted field name
    for bc_field, extracted_field in schema.output.field_map.items():
        if extracted_field in record_fields:
            data[bc_field] = record_fields[extracted_field]
    # Parent linkage as a ${{ params.X }} reference
    if schema.output.parent_field and schema.output.parent_param:
        data[schema.output.parent_field] = (
            "${{ params." + schema.output.parent_param + " }}"
        )

    return {
        "name": f"{schema.output.endpoint}_{index}",
        "action": schema.output.action,
        "endpoint": schema.output.endpoint,
        "data": data,
    }


def _json_default(obj: Any) -> Any:
    """Catch-all serializer for non-JSON-native types."""
    try:
        return asdict(obj)
    except TypeError:
        return str(obj)
